language: perl

perl:
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
  - "5.18"
#  - "5.19"

script:
  - perl release/prepare
  - ./configure --prefix=/tmp/foo
  - make
  - make check
  - make install
