language: perl

perl:
  - "5.10"
  - "5.18"

install:
  - cpanm Capture::Tiny Path::Class IPC::System::Simple

script:
  - perl release/prepare.pl
  - ./configure --prefix=/tmp/foo
  - make
  - make check
  - make install
