language: perl

perl:
  - "5.10"
  - "5.18"

install:
  - cpanm Capture::Tiny Path::Class IPC::System::Simple

script:
  - aclocal --version
  - autoconf --version
  - automake --version
  - perl release/prepare.pl
  - ./configure --prefix=/tmp/foo1
  - make
  - make check
  - make install
  - make dist
  - tar xf libfoo-1.00.tar.gz
  - cd libfoo-1.00 && ./configure --prefix=/tmp/foo2 && make && make check && make install
